export default function Head() {
    return (
        <>
            <title>Emma's Gymnastics!</title>
            <meta
                content="width=device-width, initial-scale=1"
                name="viewport"
            />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/gymicon.png" />
            {/* <link rel="preconnect" href="https://rsms.me/" />
            <link rel="stylesheet" href="https://rsms.me/inter/inter.css" /> */}
        </>
    );
}
